version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
    ports:
      - "6000:6000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
