// export const API_ENDPOINT = 'http://127.0.0.1:5000/api';
// export const API_ENDPOINT = 'https://ec2-47-129-6-189.ap-southeast-1.compute.amazonaws.com/api';
export const API_ENDPOINT = 'https://anhmok.com/ai/api';
export const AUTH_ENDPOINT = `${API_ENDPOINT}/v1/auth`;
export const USER_ENDPOINT = `${API_ENDPOINT}/v1/user`;
export const TTS_ENDPOINT = `${API_ENDPOINT}/v1/audio/speech`;
export const CHAT_COMPLETIONS_ENDPOINT = `${API_ENDPOINT}/v1/chat/completions`;
export const MODELS_ENDPOINT = `${API_ENDPOINT}/v1/models`;
export const DOMAIN_ENDPOINT = `${API_ENDPOINT}/v1/domain`;
